### ISSUE TITLE
Recipe.java todo list

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/CSC510_Group25_Project1#62]
- [ ] Allow modification of recipes
- [ ] Ensure that each ingredient is unique
- [ ] Allow creation of recipes through I/O
- [ ] Save/create/update/delete .txt files
- [ ] Null/input checks in methods, constructors
- [ ] Refactor/optimize
