### ISSUE TITLE
BuildFile.java todo list

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/CSC510_Group25_Project1#63]
BuildFile.java handles the saving and reading of .txt and .json files for object construction.

- [ ] save recipes as .txt #62 #50 
- [ ] Clean up, refactor, optimize
- [ ] Complete the following methods:
    - [ ] SaveRecipeJson
    - [ ] SaveJsonArray
