### ISSUE TITLE
MockDB.java todo list

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/CSC510_Group25_Project1#65]
MockDB.java simulates a very rudimentary database for the quantity calculator feature.

Follow the todo trail inside your IDE!

- [ ] check method inputs
- [ ] Enable Item construction via I/O     #56
- [ ] Generate unique dbIDs for every unique item (future)  #56     
- [ ] Make compatible with Item batches (maybe)        #56
- [ ] Clean up, refactor, optimize
- [ ] Complete unfinished methods (as needed)
