### ISSUE TITLE
UnitConverter.java todo list

### ISSUE THREAD

**Issue by snapcat** [CSC510-Group-25/CSC510_Group25_Project1#67]
Follow the todo trail in your IDE!

- [ ] Optimize
- [ ] Implement dry conversions
- [ ] Check math / improve precision
- [ ] Implement decimal rounding
